In [7]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [11]:
cv2.__version__

'4.5.5'

Detect the code using QRCodeDetector
Print QR detected if a QR has been detected in the image
Decode and print the decoded text
Draw a rectangle around the QR code that has been detected and show it on the screen
Save the QR region of the image to disk

In [15]:
qrDecoder = cv2.QRCodeDetector()
img = cv2.imread('./pngs/qr1.jpg')
# Detect and decode the qrcode

retval, points, straight_qrcode = qrDecoder.detectAndDecode(img)

print(retval)
print(points)
print(straight_qrcode)


# print(type(olma))
# print(type(points))
# print(type(straight_qrcode))
# print(straight_qrcode)
# print(type(points))
# if len(points)>0:

#     print('QR detected')
#     print(points)

# cv2.rectangle(img, tuple(straight_qrcode[0][0].astype(int)), tuple(straight_qrcode[0][2].astype(int)), (0, 255, 0), 3)

# cv2.imshow('QR region', img)
# print(olma.shape)


# cv2.waitKey(0)
# cv2.destroyAllWindows()

http://about.me/paulshipper/moo
[[[344.  42.]
  [484.  42.]
  [484. 182.]
  [344. 182.]]]
[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ... 255 255   0]
 [  0 255 255 ... 255   0 255]
 [  0   0   0 ... 255   0   0]]


In [9]:
img = cv2.imread('./pngs/qr.png')
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [79]:
tuple(straight_qrcode[0][0])

(65.0, 65.0)